//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Araba
    {
        public TB_Araba()
        {
            this.TB_Musteri = new HashSet<TB_Musteri>();
            this.TB_Satilan = new HashSet<TB_Satilan>();
        }
    
        public int ArabaID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> Yil { get; set; }
        public string Km { get; set; }
        public string Yakıt { get; set; }
        public string Renk { get; set; }
        public string AracTNo { get; set; }
        public string Plaka { get; set; }
        public Nullable<int> AlisFiyat { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public string TedarikciAdi { get; set; }
        public string TedarikciTel { get; set; }
        public Nullable<System.DateTime> AlindigiTarih { get; set; }
        public Nullable<int> ResimID { get; set; }
        public Nullable<int> Satildimi { get; set; }
    
        public virtual TB_Resimler TB_Resimler { get; set; }
        public virtual ICollection<TB_Musteri> TB_Musteri { get; set; }
        public virtual ICollection<TB_Satilan> TB_Satilan { get; set; }
    }
}
