//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Musteri
    {
        public TB_Musteri()
        {
            this.TB_Satilan = new HashSet<TB_Satilan>();
        }
    
        public int MusteriID { get; set; }
        public string Musteriİsim { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> ArabaID { get; set; }
        public string TC { get; set; }
    
        public virtual TB_Araba TB_Araba { get; set; }
        public virtual ICollection<TB_Satilan> TB_Satilan { get; set; }
    }
}
