//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_OtoGaleriEntities : DbContext
    {
        public DB_OtoGaleriEntities()
            : base("name=DB_OtoGaleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_Araba> TB_Araba { get; set; }
        public virtual DbSet<TB_Banka> TB_Banka { get; set; }
        public virtual DbSet<TB_MarkaModel> TB_MarkaModel { get; set; }
        public virtual DbSet<TB_Musteri> TB_Musteri { get; set; }
        public virtual DbSet<TB_Resimler> TB_Resimler { get; set; }
        public virtual DbSet<TB_Satilan> TB_Satilan { get; set; }
    }
}
