//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Banka
    {
        public TB_Banka()
        {
            this.TB_Satilan = new HashSet<TB_Satilan>();
        }
    
        public int İslemID { get; set; }
        public string İslemAciklama { get; set; }
        public Nullable<int> İslemCesidi { get; set; }
        public Nullable<int> BankadakiPara { get; set; }
        public Nullable<int> AlacakMiktari { get; set; }
        public Nullable<int> BorcMiktari { get; set; }
        public Nullable<int> KasadakiPara { get; set; }
    
        public virtual ICollection<TB_Satilan> TB_Satilan { get; set; }
    }
}
