//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Resimler
    {
        public TB_Resimler()
        {
            this.TB_Araba = new HashSet<TB_Araba>();
        }
    
        public int ResimID { get; set; }
        public Nullable<int> ArabaID { get; set; }
        public string ResimYolu { get; set; }
    
        public virtual ICollection<TB_Araba> TB_Araba { get; set; }
    }
}
