//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Satilan
    {
        public int SatisID { get; set; }
        public Nullable<int> SatisFiyat { get; set; }
        public Nullable<System.DateTime> SatisTarihi { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> ArabaID { get; set; }
        public Nullable<int> AlisFiyat { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Plaka { get; set; }
        public Nullable<int> ResimID { get; set; }
        public Nullable<int> İslemID { get; set; }
    
        public virtual TB_Araba TB_Araba { get; set; }
        public virtual TB_Banka TB_Banka { get; set; }
        public virtual TB_Musteri TB_Musteri { get; set; }
    }
}
